backend: "python"

input [
  {
    name: "image_bytes"
    data_type: TYPE_STRING
    dims: [1]
  }
]

output [
  {
    name: "preprocessed_image"
    data_type: TYPE_UINT8
    dims: [3, -1, -1]
  }
]


parameters: {
  key: "EXECUTION_ENV_PATH",
  value: {string_value: "$$TRITON_MODEL_DIRECTORY/pyenv.tar.gz"}
}
